export const LOGIN_URL = "/api/login"
export const GET_USER = "/api/getuser"
export const ADD_SERVICE = "/api/addservice"
export const ADD_USER = "/api/adduser"
export const AUDIT_HISTORY = "/api/audithistory"